### ISSUE TITLE
zig 0.12

### ISSUE THREAD

**Issue by dnut** [Syndica/sig#115]
zig 0.12 is currently scheduled for april 2: https://github.com/ziglang/zig/milestone/23

We don't need to upgrade the moment it's released, but it would be good to get ahead of any breaking changes, so we don't accumulate technical debt.

blocked until all dependencies support 0.12:

| dependency  | 0.12 support |
| --          | -- |
| base58-zig  | https://github.com/dnut/base58-zig |
| zig-network | ✅ |
| zig-cli     | ✅ |
| getty       | ✅ |
| httpz       | ✅ |
| zigdig      | https://github.com/dnut/zigdig |

**Comment by 0xNineteen** [comment]
#129
