### ISSUE TITLE
Posts explaining Sig Validator should be updated

### ISSUE THREAD

**Issue by kubanemil** [Syndica/sig#138]
### Description

I would recommend updating the names and links (and any other info) in this [article](https://blog.syndica.io/sig-engineering-1-gossip-protocol/):
- CrdsTable => [GossipTable](https://github.com/Syndica/sig/blob/c537e0fd80aeb70ebe0f041db2eb65d5de0c42fd/src/gossip/table.zig#L76)
- CrdsValue => [GossipSignedData](https://github.com/Syndica/sig/blob/c537e0fd80aeb70ebe0f041db2eb65d5de0c42fd/src/gossip/data.zig#L72)
- CrdsData => [GossipData](https://github.com/Syndica/sig/blob/c537e0fd80aeb70ebe0f041db2eb65d5de0c42fd/src/gossip/data.zig#L280)
- **etc.**

It is not crucial, but will be nice to do, so incoming contributors will dive into the new codebase faster. 
Would be helpful if someone could lead to article's markdown file (if exists), to update it.

### How to Reproduce the Bug

Look this [page](https://blog.syndica.io/sig-engineering-1-gossip-protocol/).

**Comment by 0xNineteen** [comment]
thanks for the report - will look into updating the article soon
