### ISSUE TITLE
audit: replace all uses of `std.time.milliTimestamp` as a seed with parameterized seeds or RNGs

### ISSUE THREAD

**Issue by InKryption** [Syndica/sig#176]
We should replace all uses of `std.time.milliTimestamp` as a seed that aren't obviously at the highest level of code, with a `std.Random` interface parameter, or a pointer to a concrete PRNG implementation if specific random behavior is desired/required.

This would facilitate testing by making behavior deterministic, and as well allow us to more easily identify when we could use a better source of entropy than timestamps, which are a poor source.

_Originally posted by @InKryption in https://github.com/Syndica/sig/issues/157#issuecomment-2163115441_

**Comment by 0xNineteen** [comment]
closing for now since i believe we got all this done - can reopen with specific example if we missed something
