### ISSUE TITLE
refactor: Replace byte slice fs paths with file and directory handles

### ISSUE THREAD

**Issue by InKryption** [Syndica/sig#183]
* https://github.com/Syndica/sig/blob/b68a674f8ec7bb35cd5939f102a173f8ea668fa9/src/accountsdb/index.zig#L604-L605
The disk memory allocator currently uses a path which is implicitly relative to cwd; it should be able to be relative to any arbitrary location we configure it to. One way to amend it would be to have hold a directory handle, inside of which we populate file entries whose names are just their numerical index.

* https://github.com/Syndica/sig/blob/b68a674f8ec7bb35cd5939f102a173f8ea668fa9/src/accountsdb/db.zig#L123-L132
This code would be a lot simpler and avoid allocation if `snapshots_dir` was a handle, and the functions taking `accounts_path` also took a handle.

* https://github.com/Syndica/sig/blob/b68a674f8ec7bb35cd5939f102a173f8ea668fa9/src/cmd/cmd.zig#L673-L690
Same reasoning as the former.

These are the main examples of code where using a fs handle would be superior. There are a myriad more subtle cases as well, which should be investigated and experimented with.
Another less obvious, but real benefit of passing around and re-using handles is that they become a much more obvious resource, which we can track and be mindful of, in the same way we try to do with memory via the allocator interface.

**Comment by sonicfromnewyoke** [comment]
@InKryption  WDYT, is it worth changing `AccountsDBConfig` and its corresponding field ` snapshot_dir: []const u8 = sig.VALIDATOR_DIR ++ "accounts_db",` in the scope of that issue?

**Comment by InKryption** [comment]
@sonicfromnewyoke No, I don't think that field should be changed. It has to be filled in by the CLI frontend, and in general is top level data which is used to specify how to initialize the data at the lower level (the file handle).
