### ISSUE TITLE
handle rocksdb dependencies better

### ISSUE THREAD

**Issue by dnut** [Syndica/sig#224]
This ticket exists mainly to raise attention that this ticket is relevant to sig: https://github.com/Syndica/rocksdb-zig/issues/3

Specifically, we have a mitigation in sig's CI for this (which is described as mitigation 2 in the linked ticket):

https://github.com/Syndica/sig/blob/32d9e36247db243babe07ce4b29cc77397c0ba54/.github/workflows/check.yml#L51-L52

This exists three times in check.yml. Also, if you want to build sig on any linux system, it only works if those libraries are not installed.

It would be nice to come up with a better fix, which probably means solving the underlying issue described in the linked ticket.

**Comment by Rexicon226** [comment]
can be closed with #236 merged
