### ISSUE TITLE
[Question] Hardware Requirements?

### ISSUE THREAD

**Issue by Davincible** [Syndica/sig#274]
I am trying to find the hardware requirements, but can't find it anywhere in the docs.

I am looking for a more lightweight read only node that doesn't need a massive server. Wondering if this fits that

**Comment by Davincible** [comment]
@0xNineteen why is this closed? Still waiting for an answer

**Comment by 0xNineteen** [comment]
sorry for the late reply -- sig isnt a full validator yet: we support functionality across gossip, accounts-db, and the repair stage -- all can be run on a laptop with at least 16GB of ram and ideally 10+ cpu cores for reasonable multi-threading speed
