### ISSUE TITLE
OutOfMemoryallocBuff error when running gossip

### ISSUE THREAD

**Issue by dadepo** [Syndica/sig#334]
### Zig Version

0.13.0

### Steps to Reproduce and Observed Behavior

Running gossip for a couple of hours ends up failing with the following error:

```
allocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemoryallocBuff failed with err:
```

Command executed was

`./zig-out/bin/sig -l debug gossip -n testnet -p 8001`

The error has also been reported to occur when testing extremely large amount of logs, hence this is likely from the logger running out of memory.

### Expected Behavior

Should not fail with OutOfMemoryallocBuff error

### How to Reproduce the Bug

Run Sig for long period of time

**Comment by dnut** [comment]
Does sig actually crash? I would expect it to keep running but just fail to log anything. Does it ever start logging normally again?

**Comment by dadepo** [comment]
> Does sig actually crash? I would expect it to keep running but just fail to log anything. 

Just confirmed again. It does not crash and it keeps running.

> Does it ever start logging normally again?

Nope. Left it running over the weekend, the process is still running but it each attempt to log just prints out `failed with err: error.OutOfMemoryallocBuff failed with err: error.OutOfMemory`

**Comment by dnut** [comment]
I also reproduced this last week. It's telling that it never starts logging again.

Let's say the only problem is that the logger's allocator is not given enough memory up front to handle the number of concurrent messages in the queue before they are logged. I would expect to see the logger recover and start logging again. There would be some OOM errors briefly, but then all the pending messages in the queue would be logged and freed, and then the logger should start being able to successfully log again. The errors may repeat again but I would periodically expect to see messages getting logged.

But in this case, the logger gets into a degraded state where it never logs anything again. This tells me there is something else going wrong in either the logger or the allocator that prevents it from being able to reclaim any of the memory that was used for old log messages.
