### ISSUE TITLE
How to try locally?

### ISSUE THREAD

**Issue by snawaz** [Syndica/sig#41]
It's not a bug or feature request as such. I was wondering how to run this locally and get connect requests from other nodes.

I've tried this so far:

- Pinged `api.mainnet-beta.solana.com` to get its IP address.
- Passed the `IP:80` as endpoints to `sig gossip`.

The server is started, but not getting any connection requests. Is it expected to work this way? Or some setup is still missing? One thing could be.. my local machine isn't reachable from public. Can [`ngrok`][1] help here, or I've to run it from a public address? Looking for some suggestions to try it on my machine.

<img width="1146" alt="image" src="https://github.com/Syndica/sig/assets/1185906/dd450046-7912-462a-8b84-1892696482ce">

[1]: https://www.youtube.com/watch?v=F_xNOVY96Ng

**Comment by 0xNineteen** [comment]
yeah we've found that specific entrypoints dont support gossip (not 100% sure why) -- it should work using `ping entrypoint5.mainnet-beta.solana.com` as your entrypoint (ie, `-e 86.109.15.59:8001`)
