### ISSUE TITLE
Protocol message deserialization broken on mainnet.

### ISSUE THREAD

**Issue by clarkezone** [Syndica/sig#45]
### Description

Protocol message deserialization appears broken on mainnet:

`sig!bincode.bincode.Deserializer(io.reader.Reader(*io.fixed_buffer_stream.FixedBufferStream([]const u8),error{},(function 'read'))).deserializeEnum__anon_39398 (/Users/jamesclarke/src/github.com/clarkezone/sig/src/bincode/bincode.zig:126)
sig!de.interfaces.deserializer.Deserializer(*bincode.bincode.Deserializer(io.reader.Reader(*io.fixed_buffer_stream.FixedBufferStream([]const u8),error{},(function 'read'))),error{IO,OutOfMemory,Unsupported,DuplicateField,InvalidLength,InvalidType,InvalidValue,MissingAllocator,MissingField,MissingVariant,UnknownField,UnknownVariant},bincode.bincode.Deserializer(io.reader.Reader(*io.fixed_buffer_stream.FixedBufferStream([]const u8),error{},(function 'read'))).CustomDeser,null,.{.deserializeAny = null, .deserializeBool = (function 'deserializeBool'), .deserializeEnum = (function 'deserializeEnum'), .deserializeFloat = (function 'deserializeFloat'), .deserializeIgnored = null, .deserializeInt = (function 'deserializeInt'), .deserializeMap = (function 'deserializeMap'), .deserializeOptional = (function 'deserializeOptional'), .deserializeSeq = (function 'deserializeSeq'), .deserializeString = null, .deserializeStruct = null, .deserializeUnion = null, .deserializeVoid = (function 'deserializeVoid')}).getty.Deserializer.deserializeEnum__anon_35679 (/Users/jamesclarke/.cache/zig/p/12209398657d260abcd6dae946d8da4cd3057b8c7990608476a9f8011aae570d2ebb/src/de/interfaces/deserializer.zig:162)
sig!de.blocks.enum.deserialize__anon_35678 (/Users/jamesclarke/.cache/zig/p/12209398657d260abcd6dae946d8da4cd3057b8c7990608476a9f8011aae570d2ebb/src/de/blocks/enum.zig:29)
sig!de.deserialize.deserialize__anon_34376 (/Users/jamesclarke/.cache/zig/p/12209398657d260abcd6dae946d8da4cd3057b8c7990608476a9f8011aae570d2ebb/src/de/deserialize.zig:41)
sig!bincode.bincode.Deserializer(io.reader.Reader(*io.fixed_buffer_stream.FixedBufferStream([]const u8),error{},(function 'read'))).CustomDeser.deserialize__anon_32954 (/Users/jamesclarke/src/github.com/clarkezone/sig/src/bincode/bincode.zig:264)
sig!de.deserialize.deserialize__anon_22235 (/Users/jamesclarke/.cache/zig/p/12209398657d260abcd6dae946d8da4cd3057b8c7990608476a9f8011aae570d2ebb/src/de/deserialize.zig:41)
sig!bincode.bincode.readFromSlice__anon_22132 (/Users/jamesclarke/src/github.com/clarkezone/sig/src/bincode/bincode.zig:728)
sig!gossip.gossip_service.GossipService.verifyPackets (/Users/jamesclarke/src/github.com/clarkezone/sig/src/gossip/gossip_service.zig:271)
sig!Thread.callFn__anon_21534 (/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/Thread.zig:433)
sig!Thread.PosixThreadImpl.spawn__anon_20343.Instance.entryFn (/opt/homebrew/Cellar/zig/0.11.0/lib/zig/std/Thread.zig:685)
libsystem_pthread.dylib!_pthread_start (Unknown Source:0)`

### How to Reproduce the Bug

`./zig-out/bin/sig gossip -e 86.109.15.59:8001`

Result:
time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

time=2023-11-03T11:38:32Z level=debug  failed to deserialize protocol message: 1

**Comment by clarkezone** [comment]
I can confirm this repos on both macOS and linux with zig 0.11.0.

**Comment by snawaz** [comment]
> I can confirm this repos on both macOS and linux with zig 0.11.0.

Please also post the processors/endianness as well.

**Comment by clarkezone** [comment]
> > I can confirm this repos on both macOS and linux with zig 0.11.0.
> 
> 
> 
> Please also post the processors/endianness as well.

MacOS Apple Silicon M1: Little
Linux: AMD64: Little

**Comment by 0xNineteen** [comment]
thanks for the heads up - rn theres a backlog of gossip-related PRs that would make a fix a little fuzzy with merge conflicts and such - my plans to checkout this bug once the PRs are merged (should be soon)

**Comment by clarkezone** [comment]
> thanks for the heads up - rn theres a backlog of gossip-related PRs that would make a fix a little fuzzy with merge conflicts and such - my plans to checkout this bug once the PRs are merged (should be soon)

SG.  I did some debugging but couldn't see an obvious cause.  Once the PR's are merged I'll try again.

**Comment by dnut** [comment]
Fixed in #48 and merged into gossip optimization branch. Will merge to main with #39.

**Comment by clarkezone** [comment]
Thanks, confirm this is now fixed.
