### ISSUE TITLE
Ubuntu Linux support broken by PR fix(prometheus): pr feedback

### ISSUE THREAD

**Issue by clarkezone** [Syndica/sig#63]
### Description

Doing some testing recently, I discovered that [fix(prometheus): pr feedback](https://github.com/Syndica/sig/commit/7eca0e45b30901f5f4d8cde28edb6731a68f1f24) appears to have broken Ubuntu Linux support for sig running in gossip mode.  This was first discovered at the tip of main and isolated by working back through commits in main to find where this broken.  Using this process, I can confirm that  [feat(cmd): cli option for spy node](https://github.com/Syndica/sig/commit/9972bedd50b1c76d6a8fc7dfe4e1c48a85a0d7d1) is the first commit that works on Ubuntu.  

I can separately confirm that this problem does not repro on MacOS suggesting a Linux specific issue.  I have not verified with other distros beyond Ubuntu 22.04.

### How to Reproduce the Bug

With an environment that matches the following:

```bash
➜  sig git:(9972bed) ✗ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
➜  sig git:(9972bed) ✗ uname -a
Linux clarkezonedevbox5-tr 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
➜  sig git:(9972bed) ✗ zig version
0.11.0
```

Checkout tip of main and verify broken. 

```bash
➜  sig git:(main) ✗ rm -rf zig-out
➜  sig git:(main) ✗ rm -rf zig-cache
➜  sig git:(main) ✗ git checkout main
Your branch is up to date with 'origin/main'.
➜  sig git:(main) ✗ zig build run -- gossip -e 86.109.15.59:8001
gossip port: 8001
entrypoints: { net.net.SocketAddr{ .V4 = net.net.SocketAddrV4{ .ip = net.net.Ipv4Addr{ ... }, .port = 8001 } } }
thread 582066 panic: index out of bounds: index 18446744073709551578, len 64
Unable to dump stack trace: InvalidElfMagic
qemu: uncaught target signal 6 (Aborted) - core dumped
run sig: error: the following command terminated unexpectedly:
/home/james/src/github.com/clarkezone/sig/zig-out/bin/sig gossip -e 86.109.15.59:8001
Build Summary: 9/11 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run sig failure
error: the following build command failed with exit code 1:
/home/james/src/github.com/clarkezone/sig/zig-cache/o/fc46972c005420b778f256e0192a22cc/build /home/james/.local/share/zigup/0.11.0/files/zig /home/james/src/github.com/clarkezone/sig /home/james/src/github.com/clarkezone/sig/zig-cache /home/james/.cache/zig run -- gossip -e 86.109.15.59:8001
```

Checkout commit that introduced problem verify still broken
```bash
➜  sig git:(main) ✗ rm -rf zig-out
➜  sig git:(main) ✗ rm -rf zig-cache
➜ sig git:(7eca0e4) ✗ git checkout 7eca0e45b30901f5f4d8cde28edb6731a68f1f24
HEAD is now at 7eca0e4 fix(prometheus): pr feedback
➜ sig git:(7eca0e4) ✗ zig build run -- gossip -e 86.109.15.59:8001
gossip port: 8001
entrypoints: { net.net.SocketAddr{ .V4 = net.net.SocketAddrV4{ .ip = net.net.Ipv4Addr{ ... }, .port = 8001 } } }
thread 583019 panic: index out of bounds: index 18446744073709551578, len 64
Unable to dump stack trace: InvalidElfMagic
time=qemu: uncaught target signal 6 (Aborted) - core dumped
run sig: error: the following command terminated unexpectedly:
/home/james/src/github.com/clarkezone/sig/zig-out/bin/sig gossip -e 86.109.15.59:8001
Build Summary: 9/11 steps succeeded; 1 failed (disable with --summary none)
run transitive failure
└─ run sig failure
error: the following build command failed with exit code 1:
/home/james/src/github.com/clarkezone/sig/zig-cache/o/fc46972c005420b778f256e0192a22cc/build /home/james/.local/share/zigup/0.11.0/files/zig /home/james/src/github.com/clarkezone/sig /home/james/src/github.com/clarkezone/sig/zig-cache /home/james/.cache/zig run -- gossip -e 86.109.15.59:8001
```

Checkout previous commit, verify everything working
```bash
➜ sig git:(7eca0e4) ✗ rm -rf zig-out
➜  sig git:(7eca0e4) ✗ rm -rf zig-cache
➜  sig git:(7eca0e4) ✗ git checkout 9972bedd50b1c76d6a8fc7dfe4e1c48a85a0d7d1
Previous HEAD position was 7eca0e4 fix(prometheus): pr feedback
HEAD is now at 9972bed feat(cmd): cli option for spy node
➜  sig git:(9972bed) ✗ zig build run -- gossip -e 86.109.15.59:8001
gossip port: 8001
entrypoints: { net.net.SocketAddr{ .V4 = net.net.SocketAddrV4{ .ip = net.net.Ipv4Addr{ ... }, .port
= 8001 } } }
time=2024-01-01T01:04:18Z level=debug  using n_threads in gossip: 8

time=2024-01-01T01:04:18Z level=debug  started server listener on 0.0.0.0:8001
time=2024-01-01T01:04:18Z level=debug  accepting new connections
time=2024-01-01T01:04:18Z level=debug  handle batch pull_resp took 10392625 with 1 items @1

time=2024-01-01T01:04:18Z level=debug  handle batch crds_trim took 41008 with 1 items @1

time=2024-01-01T01:04:18Z level=debug  1 messages processed in 17995924ns

time=2024-01-01T01:04:18Z level=debug  handle batch pull_resp took 2257343 with 18 items @20

time=2024-01-01T01:04:19Z level=info from_endpoint="86.109.15.59:8001" from_pubkey="CakcnaRDHka2gXyf
bEd2d3xsvkJkqsLw2akB3zsN1D2S"  gossip: recv ping
time=2024-01-01T01:04:19Z level=debug  handle batch ping took 11604853 with 1 items @20

time=2024-01-01T01:04:19Z level=debug  handle batch crds_trim took 6162 with 1 items @20

time=2024-01-01T01:04:19Z level=debug  20 messages processed in 36835362ns

time=2024-01-01T01:04:19Z level=debug  handle batch pull_resp took 252416 with 22 items @42

time=2024-01-01T01:04:19Z level=debug  handle batch crds_trim took 3106 with 1 items @42

time=2024-01-01T01:04:19Z level=debug  42 messages processed in 46335084ns

time=2024-01-01T01:04:19Z level=debug  handle batch pull_resp took 180831 with 14 items @56

time=2024-01-01T01:04:19Z level=debug  handle batch crds_trim took 2445 with 1 items @56

time=2024-01-01T01:04:19Z level=debug  56 messages processed in 57048632ns
```

### Additional Context

The issue appears to be some kind of low-level panic that I'm not familiar with, don't know if it relates to the fact I'm running Ubuntu in in a VM as qemu is mentioned.

```
➜  sig git:(7eca0e4) ✗ ./zig-out/bin/sig gossip -e 86.109.15.59:8001
gossip port: 8001
entrypoints: { net.net.SocketAddr{ .V4 = net.net.SocketAddrV4{ .ip = net.net.Ipv4Addr{ ... }, .port = 8001 } } }
thread 585439 panic: index out of bounds: index 18446744073709551578, len 64
Panicked during a panic. Aborting.
qemu: uncaught target signal 6 (Aborted) - core dumped
[1]    585435 IOT instruction (core dumped)  ./zig-out/bin/sig gossip -e 86.109.15.59:8001
```

I wasn't able to debug the failure using LLDB:

```bash
➜  sig git:(7eca0e4) ✗ lldb -- ./zig-out/bin/sig gossip -e 86.109.15.59:8001
(lldb) target create "./zig-out/bin/sig"
Current executable set to '/home/james/src/github.com/clarkezone/sig/zig-out/bin/sig' (aarch64).
(lldb) settings set -- target.run-args  "gossip" "-e" "86.109.15.59:8001"
(lldb) process launch
error: Lost debug server connection
```

**Comment by dnut** [comment]
Thanks for this high quality bug report. Looks like this is from one of my changes. We definitely need Sig to work in Linux. I'll see if I can reproduce this.

**Comment by dnut** [comment]
I tried reproducing this in a few linux environments, including a qemu vm that looks like yours with the same version of ubuntu. I haven't yet had any luck reproducing the same error.

In your logs I'm seeing at least two distinct problems.

------
```
thread 582066 panic: index out of bounds: index 18446744073709551578, len 64
```
This looks like a normal zig panic for using an invalid index. The index is 38 less than 2^64 which hints that there may an issue with arithmetic calculating an index. Maybe there's a wrapping subtraction that goes below zero. If you repeat this test, does it always have the same result, or is it flaky?

I took a quick look at the commit you've narrowed this to, and it's not yet apparent to me where an index out of bounds error could be coming from. I could spend some more time on it, but it would be a lot easier with a stack trace.

------
```
Unable to dump stack trace: InvalidElfMagic
qemu: uncaught target signal 6 (Aborted) - core dumped
```
I haven't seen this before and I'm not sure exactly what's going wrong. This prevents us from seeing the stack trace, which makes it a lot harder to track down this bug. I tried to reproduce this specific issue by adding some code that triggers an index out of bounds error. But in my qemu vm it printed the stack trace without a problem. Do you ever see a stack trace when a zig program panics in this ubuntu vm?

The error is complaining that a file is not a proper linux executable. The standard library tries to read some files to get debug information in order to print a stack trace. These files may be the currently executing binary (sig) or a file that it links to. It returns InvalidElfMagic when one of those files is not formatted as expected. It seems like there is some kind of binary incompatibility with the files in your ubuntu vm.

Could you please share some more details about your environment? How did you configured the virtual machine? What is the host operating system? Did you create it just for this test? Is it a vanilla installation of ubuntu, or have you made some modifications to the system? Where did you get zig from? Did you copy any files from another system with a different architecture into the system where you saw this error? Did you clone sig directly from github into the vm?

**Comment by clarkezone** [comment]
Thx for taking a look so promptly!  I will get back to you on the first question about the invalid index.  For the environment questions:

VM is configured with a 200GB drive, 10 cores and is hosted in Hyperv on 64 bit Windows 11 pro build 22631.2661 running on a AMD Ryzen Threadripper 3970X.

VM in question is my primary Linux dev VM and as such has a bunch of tools installed and is not a clean environment.  I'm in the process of bringing up a test VM with same config and ubuntu build but vanilla to eliminate that part (should have an update later today or tomorrow).

zig was installed using zigup.

Did not copy any files from another system.

Sig cloned from main branch of my fork of sig upstream which is sync'd to syndica tip of tree.  I'm checking out specific commits as you can see in repro steps and have no unstaged changes.

**Comment by clarkezone** [comment]
Update: I did a quick smoke test and looks like something is funky with my dev VM as issue doesn't repro with a clean Ubuntu same version, same host environment.  I plan on doing a couple of quick follow-up tests later and will then close this issue out unless follow-up yields anything actionable.
