### ISSUE TITLE
Sig readme instructions no longer work for `Zig Run` case

### ISSUE THREAD

**Issue by clarkezone** [Syndica/sig#77]
### Description

Readme explains how to run Sig via `zig run`  These instructions no longer work (pre-compiling binary works fine)

### How to Reproduce the Bug

1. Sync to tip of `main` branch
2. Change into `src` dir
3. Attempt to run using instructions composed from readme (either verbatim or adding args for gossip)
```zig 
zig run main.zig -- gossip --entrypoint 34.83.231.102:8001 \
    --entrypoint 145.40.67.83:8001 \
    --entrypoint 147.75.38.117:8001 \
    --entrypoint 145.40.93.177:8001 \
    --entrypoint 86.109.15.59:8001
```

result:
```bash
cmd/cmd.zig:2:21: error: no package named 'zig-cli' available within package 'root'
const cli = @import("zig-cli");
```

**Comment by 0xNineteen** [comment]
it should be `zig build run -- gossip ...` which seems to run ok on main
