### ISSUE TITLE
LruCache locks don't work

### ISSUE THREAD

**Issue by dnut** [Syndica/sig#89]
The locks are released within the if-statement before executing any of the logic that should be locked

code: https://github.com/Syndica/sig/blob/69b9a8e871698371902cb1b60a1d3f046a502c4d/src/common/lru.zig#L124C17-L124C41

something like this should work:
```zig
if (kind == .locking) self.mux.lock();
defer if (kind == .locking) self.mux.unlock();
```

**Comment by ultd** [comment]
Ah yes defer is block scoped in Zig, not function scoped. Can you push a PR/fix?
